/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AskAQuestionRouteImport } from './routes/ask-a-question'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DoctorOnboardingRouteImport } from './routes/doctor-onboarding'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as InsuranceEligibilityRouteImport } from './routes/insurance-eligibility'
import { Route as NoCostEmiRouteImport } from './routes/no-cost-emi'
import { Route as PatientHelpRouteImport } from './routes/patient-help'
import { Route as PregnancyDueDateCalculatorRouteImport } from './routes/pregnancy-due-date-calculator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as DoctorsSlugRouteImport } from './routes/doctors/$slug'
import { Route as HospitalsIndexRouteImport } from './routes/hospitals/index'
import { Route as HospitalsSlugRouteImport } from './routes/hospitals/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsCityRouteImport } from './routes/locations/$city'
import { Route as SpecialitiesSlugRouteImport } from './routes/specialities/$slug'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments/index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAQuestionRoute = AskAQuestionRouteImport.update({
  id: '/ask-a-question',
  path: '/ask-a-question',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorOnboardingRoute = DoctorOnboardingRouteImport.update({
  id: '/doctor-onboarding',
  path: '/doctor-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceEligibilityRoute = InsuranceEligibilityRouteImport.update({
  id: '/insurance-eligibility',
  path: '/insurance-eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const NoCostEmiRoute = NoCostEmiRouteImport.update({
  id: '/no-cost-emi',
  path: '/no-cost-emi',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHelpRoute = PatientHelpRouteImport.update({
  id: '/patient-help',
  path: '/patient-help',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnancyDueDateCalculatorRoute =
  PregnancyDueDateCalculatorRouteImport.update({
    id: '/pregnancy-due-date-calculator',
    path: '/pregnancy-due-date-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsIndexRoute = HospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsSlugRoute = HospitalsSlugRouteImport.update({
  id: '/hospitals/$slug',
  path: '/hospitals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitiesSlugRoute = SpecialitiesSlugRouteImport.update({
  id: '/specialities/$slug',
  path: '/specialities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask-a-question': typeof AskAQuestionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/doctor-onboarding': typeof DoctorOnboardingRoute
  '/faqs': typeof FaqsRoute
  '/insurance-eligibility': typeof InsuranceEligibilityRoute
  '/no-cost-emi': typeof NoCostEmiRoute
  '/patient-help': typeof PatientHelpRoute
  '/pregnancy-due-date-calculator': typeof PregnancyDueDateCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask-a-question': typeof AskAQuestionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/doctor-onboarding': typeof DoctorOnboardingRoute
  '/faqs': typeof FaqsRoute
  '/insurance-eligibility': typeof InsuranceEligibilityRoute
  '/no-cost-emi': typeof NoCostEmiRoute
  '/patient-help': typeof PatientHelpRoute
  '/pregnancy-due-date-calculator': typeof PregnancyDueDateCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/hospitals': typeof HospitalsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask-a-question': typeof AskAQuestionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/doctor-onboarding': typeof DoctorOnboardingRoute
  '/faqs': typeof FaqsRoute
  '/insurance-eligibility': typeof InsuranceEligibilityRoute
  '/no-cost-emi': typeof NoCostEmiRoute
  '/patient-help': typeof PatientHelpRoute
  '/pregnancy-due-date-calculator': typeof PregnancyDueDateCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/ask-a-question'
    | '/careers'
    | '/contact'
    | '/cost'
    | '/doctor-onboarding'
    | '/faqs'
    | '/insurance-eligibility'
    | '/no-cost-emi'
    | '/patient-help'
    | '/pregnancy-due-date-calculator'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/admin/signup'
    | '/blog/$slug'
    | '/doctors/$slug'
    | '/hospitals/$slug'
    | '/locations/$city'
    | '/specialities/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/blog/'
    | '/doctors/'
    | '/hospitals/'
    | '/locations/'
    | '/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/ask-a-question'
    | '/careers'
    | '/contact'
    | '/cost'
    | '/doctor-onboarding'
    | '/faqs'
    | '/insurance-eligibility'
    | '/no-cost-emi'
    | '/patient-help'
    | '/pregnancy-due-date-calculator'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/admin/signup'
    | '/blog/$slug'
    | '/doctors/$slug'
    | '/hospitals/$slug'
    | '/locations/$city'
    | '/specialities/$slug'
    | '/treatments/$slug'
    | '/admin'
    | '/blog'
    | '/doctors'
    | '/hospitals'
    | '/locations'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/ask-a-question'
    | '/careers'
    | '/contact'
    | '/cost'
    | '/doctor-onboarding'
    | '/faqs'
    | '/insurance-eligibility'
    | '/no-cost-emi'
    | '/patient-help'
    | '/pregnancy-due-date-calculator'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/admin/signup'
    | '/blog/$slug'
    | '/doctors/$slug'
    | '/hospitals/$slug'
    | '/locations/$city'
    | '/specialities/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/blog/'
    | '/doctors/'
    | '/hospitals/'
    | '/locations/'
    | '/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AskAQuestionRoute: typeof AskAQuestionRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CostRoute: typeof CostRoute
  DoctorOnboardingRoute: typeof DoctorOnboardingRoute
  FaqsRoute: typeof FaqsRoute
  InsuranceEligibilityRoute: typeof InsuranceEligibilityRoute
  NoCostEmiRoute: typeof NoCostEmiRoute
  PatientHelpRoute: typeof PatientHelpRoute
  PregnancyDueDateCalculatorRoute: typeof PregnancyDueDateCalculatorRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  AdminSignupRoute: typeof AdminSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  HospitalsSlugRoute: typeof HospitalsSlugRoute
  LocationsCityRoute: typeof LocationsCityRoute
  SpecialitiesSlugRoute: typeof SpecialitiesSlugRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HospitalsIndexRoute: typeof HospitalsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-a-question': {
      id: '/ask-a-question'
      path: '/ask-a-question'
      fullPath: '/ask-a-question'
      preLoaderRoute: typeof AskAQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-onboarding': {
      id: '/doctor-onboarding'
      path: '/doctor-onboarding'
      fullPath: '/doctor-onboarding'
      preLoaderRoute: typeof DoctorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-eligibility': {
      id: '/insurance-eligibility'
      path: '/insurance-eligibility'
      fullPath: '/insurance-eligibility'
      preLoaderRoute: typeof InsuranceEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-cost-emi': {
      id: '/no-cost-emi'
      path: '/no-cost-emi'
      fullPath: '/no-cost-emi'
      preLoaderRoute: typeof NoCostEmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-help': {
      id: '/patient-help'
      path: '/patient-help'
      fullPath: '/patient-help'
      preLoaderRoute: typeof PatientHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnancy-due-date-calculator': {
      id: '/pregnancy-due-date-calculator'
      path: '/pregnancy-due-date-calculator'
      fullPath: '/pregnancy-due-date-calculator'
      preLoaderRoute: typeof PregnancyDueDateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/': {
      id: '/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof HospitalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$slug': {
      id: '/hospitals/$slug'
      path: '/hospitals/$slug'
      fullPath: '/hospitals/$slug'
      preLoaderRoute: typeof HospitalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialities/$slug': {
      id: '/specialities/$slug'
      path: '/specialities/$slug'
      fullPath: '/specialities/$slug'
      preLoaderRoute: typeof SpecialitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AskAQuestionRoute: AskAQuestionRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CostRoute: CostRoute,
  DoctorOnboardingRoute: DoctorOnboardingRoute,
  FaqsRoute: FaqsRoute,
  InsuranceEligibilityRoute: InsuranceEligibilityRoute,
  NoCostEmiRoute: NoCostEmiRoute,
  PatientHelpRoute: PatientHelpRoute,
  PregnancyDueDateCalculatorRoute: PregnancyDueDateCalculatorRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  AdminSignupRoute: AdminSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  HospitalsSlugRoute: HospitalsSlugRoute,
  LocationsCityRoute: LocationsCityRoute,
  SpecialitiesSlugRoute: SpecialitiesSlugRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
