/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AskAQuestionRouteImport } from './routes/ask-a-question'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DoctorOnboardingRouteImport } from './routes/doctor-onboarding'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as EmiCalculatorRouteImport } from './routes/emi-calculator'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InsuranceEligibilityRouteImport } from './routes/insurance-eligibility'
import { Route as NoCostEmiRouteImport } from './routes/no-cost-emi'
import { Route as PatientHelpRouteImport } from './routes/patient-help'
import { Route as PregnancyDueDateCalculatorRouteImport } from './routes/pregnancy-due-date-calculator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDoctorsDotxmlRouteImport } from './routes/sitemap-doctors[.]xml'
import { Route as SitemapHospitalsDotxmlRouteImport } from './routes/sitemap-hospitals[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SurgeryCostCalculatorRouteImport } from './routes/surgery-cost-calculator'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ConditionsIndexRouteImport } from './routes/conditions/index'
import { Route as ConditionsSlugRouteImport } from './routes/conditions/$slug'
import { Route as CostSlugRouteImport } from './routes/cost_.$slug'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as DoctorsSlugRouteImport } from './routes/doctors/$slug'
import { Route as HospitalsIndexRouteImport } from './routes/hospitals/index'
import { Route as HospitalsSlugRouteImport } from './routes/hospitals/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsCityRouteImport } from './routes/locations/$city'
import { Route as ReviewsWriteRouteImport } from './routes/reviews_.write'
import { Route as SpecialitiesIndexRouteImport } from './routes/specialities/index'
import { Route as SpecialitiesSlugRouteImport } from './routes/specialities/$slug'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments/index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments/$slug'
import { Route as SpecialitiesSlugCityRouteImport } from './routes/specialities/$slug_.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAQuestionRoute = AskAQuestionRouteImport.update({
  id: '/ask-a-question',
  path: '/ask-a-question',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorOnboardingRoute = DoctorOnboardingRouteImport.update({
  id: '/doctor-onboarding',
  path: '/doctor-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiCalculatorRoute = EmiCalculatorRouteImport.update({
  id: '/emi-calculator',
  path: '/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceEligibilityRoute = InsuranceEligibilityRouteImport.update({
  id: '/insurance-eligibility',
  path: '/insurance-eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const NoCostEmiRoute = NoCostEmiRouteImport.update({
  id: '/no-cost-emi',
  path: '/no-cost-emi',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHelpRoute = PatientHelpRouteImport.update({
  id: '/patient-help',
  path: '/patient-help',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnancyDueDateCalculatorRoute =
  PregnancyDueDateCalculatorRouteImport.update({
    id: '/pregnancy-due-date-calculator',
    path: '/pregnancy-due-date-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDoctorsDotxmlRoute = SitemapDoctorsDotxmlRouteImport.update({
  id: '/sitemap-doctors.xml',
  path: '/sitemap-doctors.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapHospitalsDotxmlRoute = SitemapHospitalsDotxmlRouteImport.update({
  id: '/sitemap-hospitals.xml',
  path: '/sitemap-hospitals.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeryCostCalculatorRoute = SurgeryCostCalculatorRouteImport.update({
  id: '/surgery-cost-calculator',
  path: '/surgery-cost-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CostSlugRoute = CostSlugRouteImport.update({
  id: '/cost_/$slug',
  path: '/cost/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsIndexRoute = HospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsSlugRoute = HospitalsSlugRouteImport.update({
  id: '/hospitals/$slug',
  path: '/hospitals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsWriteRoute = ReviewsWriteRouteImport.update({
  id: '/reviews_/write',
  path: '/reviews/write',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitiesIndexRoute = SpecialitiesIndexRouteImport.update({
  id: '/specialities/',
  path: '/specialities/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitiesSlugRoute = SpecialitiesSlugRouteImport.update({
  id: '/specialities/$slug',
  path: '/specialities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitiesSlugCityRoute = SpecialitiesSlugCityRouteImport.update({
  id: '/specialities/$slug_/$city',
  path: '/specialities/$slug/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask-a-question': typeof AskAQuestionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/doctor-onboarding': typeof DoctorOnboardingRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance-eligibility': typeof InsuranceEligibilityRoute
  '/no-cost-emi': typeof NoCostEmiRoute
  '/patient-help': typeof PatientHelpRoute
  '/pregnancy-due-date-calculator': typeof PregnancyDueDateCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-doctors.xml': typeof SitemapDoctorsDotxmlRoute
  '/sitemap-hospitals.xml': typeof SitemapHospitalsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surgery-cost-calculator': typeof SurgeryCostCalculatorRoute
  '/terms': typeof TermsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/cost/$slug': typeof CostSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/reviews/write': typeof ReviewsWriteRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/specialities/': typeof SpecialitiesIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/specialities/$slug/$city': typeof SpecialitiesSlugCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask-a-question': typeof AskAQuestionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/doctor-onboarding': typeof DoctorOnboardingRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance-eligibility': typeof InsuranceEligibilityRoute
  '/no-cost-emi': typeof NoCostEmiRoute
  '/patient-help': typeof PatientHelpRoute
  '/pregnancy-due-date-calculator': typeof PregnancyDueDateCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-doctors.xml': typeof SitemapDoctorsDotxmlRoute
  '/sitemap-hospitals.xml': typeof SitemapHospitalsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surgery-cost-calculator': typeof SurgeryCostCalculatorRoute
  '/terms': typeof TermsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/cost/$slug': typeof CostSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/reviews/write': typeof ReviewsWriteRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/hospitals': typeof HospitalsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/specialities': typeof SpecialitiesIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/specialities/$slug/$city': typeof SpecialitiesSlugCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ask-a-question': typeof AskAQuestionRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/doctor-onboarding': typeof DoctorOnboardingRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance-eligibility': typeof InsuranceEligibilityRoute
  '/no-cost-emi': typeof NoCostEmiRoute
  '/patient-help': typeof PatientHelpRoute
  '/pregnancy-due-date-calculator': typeof PregnancyDueDateCalculatorRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-doctors.xml': typeof SitemapDoctorsDotxmlRoute
  '/sitemap-hospitals.xml': typeof SitemapHospitalsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/surgery-cost-calculator': typeof SurgeryCostCalculatorRoute
  '/terms': typeof TermsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/cost_/$slug': typeof CostSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/locations/$city': typeof LocationsCityRoute
  '/reviews_/write': typeof ReviewsWriteRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/specialities/': typeof SpecialitiesIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/specialities/$slug_/$city': typeof SpecialitiesSlugCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/ask-a-question'
    | '/careers'
    | '/contact'
    | '/cost'
    | '/doctor-onboarding'
    | '/editorial-policy'
    | '/emi-calculator'
    | '/faqs'
    | '/forgot-password'
    | '/insurance-eligibility'
    | '/no-cost-emi'
    | '/patient-help'
    | '/pregnancy-due-date-calculator'
    | '/privacy'
    | '/reset-password'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap-doctors.xml'
    | '/sitemap-hospitals.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/surgery-cost-calculator'
    | '/terms'
    | '/admin/signup'
    | '/blog/$slug'
    | '/conditions/$slug'
    | '/cost/$slug'
    | '/doctors/$slug'
    | '/hospitals/$slug'
    | '/locations/$city'
    | '/reviews/write'
    | '/specialities/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/blog/'
    | '/conditions/'
    | '/doctors/'
    | '/hospitals/'
    | '/locations/'
    | '/specialities/'
    | '/treatments/'
    | '/specialities/$slug/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/ask-a-question'
    | '/careers'
    | '/contact'
    | '/cost'
    | '/doctor-onboarding'
    | '/editorial-policy'
    | '/emi-calculator'
    | '/faqs'
    | '/forgot-password'
    | '/insurance-eligibility'
    | '/no-cost-emi'
    | '/patient-help'
    | '/pregnancy-due-date-calculator'
    | '/privacy'
    | '/reset-password'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap-doctors.xml'
    | '/sitemap-hospitals.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/surgery-cost-calculator'
    | '/terms'
    | '/admin/signup'
    | '/blog/$slug'
    | '/conditions/$slug'
    | '/cost/$slug'
    | '/doctors/$slug'
    | '/hospitals/$slug'
    | '/locations/$city'
    | '/reviews/write'
    | '/specialities/$slug'
    | '/treatments/$slug'
    | '/admin'
    | '/blog'
    | '/conditions'
    | '/doctors'
    | '/hospitals'
    | '/locations'
    | '/specialities'
    | '/treatments'
    | '/specialities/$slug/$city'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/ask-a-question'
    | '/careers'
    | '/contact'
    | '/cost'
    | '/doctor-onboarding'
    | '/editorial-policy'
    | '/emi-calculator'
    | '/faqs'
    | '/forgot-password'
    | '/insurance-eligibility'
    | '/no-cost-emi'
    | '/patient-help'
    | '/pregnancy-due-date-calculator'
    | '/privacy'
    | '/reset-password'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap-doctors.xml'
    | '/sitemap-hospitals.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/surgery-cost-calculator'
    | '/terms'
    | '/admin/signup'
    | '/blog/$slug'
    | '/conditions/$slug'
    | '/cost_/$slug'
    | '/doctors/$slug'
    | '/hospitals/$slug'
    | '/locations/$city'
    | '/reviews_/write'
    | '/specialities/$slug'
    | '/treatments/$slug'
    | '/admin/'
    | '/blog/'
    | '/conditions/'
    | '/doctors/'
    | '/hospitals/'
    | '/locations/'
    | '/specialities/'
    | '/treatments/'
    | '/specialities/$slug_/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AskAQuestionRoute: typeof AskAQuestionRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CostRoute: typeof CostRoute
  DoctorOnboardingRoute: typeof DoctorOnboardingRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  EmiCalculatorRoute: typeof EmiCalculatorRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsuranceEligibilityRoute: typeof InsuranceEligibilityRoute
  NoCostEmiRoute: typeof NoCostEmiRoute
  PatientHelpRoute: typeof PatientHelpRoute
  PregnancyDueDateCalculatorRoute: typeof PregnancyDueDateCalculatorRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDoctorsDotxmlRoute: typeof SitemapDoctorsDotxmlRoute
  SitemapHospitalsDotxmlRoute: typeof SitemapHospitalsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurgeryCostCalculatorRoute: typeof SurgeryCostCalculatorRoute
  TermsRoute: typeof TermsRoute
  AdminSignupRoute: typeof AdminSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  CostSlugRoute: typeof CostSlugRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  HospitalsSlugRoute: typeof HospitalsSlugRoute
  LocationsCityRoute: typeof LocationsCityRoute
  ReviewsWriteRoute: typeof ReviewsWriteRoute
  SpecialitiesSlugRoute: typeof SpecialitiesSlugRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HospitalsIndexRoute: typeof HospitalsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  SpecialitiesIndexRoute: typeof SpecialitiesIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
  SpecialitiesSlugCityRoute: typeof SpecialitiesSlugCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-a-question': {
      id: '/ask-a-question'
      path: '/ask-a-question'
      fullPath: '/ask-a-question'
      preLoaderRoute: typeof AskAQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-onboarding': {
      id: '/doctor-onboarding'
      path: '/doctor-onboarding'
      fullPath: '/doctor-onboarding'
      preLoaderRoute: typeof DoctorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi-calculator': {
      id: '/emi-calculator'
      path: '/emi-calculator'
      fullPath: '/emi-calculator'
      preLoaderRoute: typeof EmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-eligibility': {
      id: '/insurance-eligibility'
      path: '/insurance-eligibility'
      fullPath: '/insurance-eligibility'
      preLoaderRoute: typeof InsuranceEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-cost-emi': {
      id: '/no-cost-emi'
      path: '/no-cost-emi'
      fullPath: '/no-cost-emi'
      preLoaderRoute: typeof NoCostEmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-help': {
      id: '/patient-help'
      path: '/patient-help'
      fullPath: '/patient-help'
      preLoaderRoute: typeof PatientHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnancy-due-date-calculator': {
      id: '/pregnancy-due-date-calculator'
      path: '/pregnancy-due-date-calculator'
      fullPath: '/pregnancy-due-date-calculator'
      preLoaderRoute: typeof PregnancyDueDateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-doctors.xml': {
      id: '/sitemap-doctors.xml'
      path: '/sitemap-doctors.xml'
      fullPath: '/sitemap-doctors.xml'
      preLoaderRoute: typeof SitemapDoctorsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-hospitals.xml': {
      id: '/sitemap-hospitals.xml'
      path: '/sitemap-hospitals.xml'
      fullPath: '/sitemap-hospitals.xml'
      preLoaderRoute: typeof SitemapHospitalsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgery-cost-calculator': {
      id: '/surgery-cost-calculator'
      path: '/surgery-cost-calculator'
      fullPath: '/surgery-cost-calculator'
      preLoaderRoute: typeof SurgeryCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost_/$slug': {
      id: '/cost_/$slug'
      path: '/cost/$slug'
      fullPath: '/cost/$slug'
      preLoaderRoute: typeof CostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/': {
      id: '/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof HospitalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$slug': {
      id: '/hospitals/$slug'
      path: '/hospitals/$slug'
      fullPath: '/hospitals/$slug'
      preLoaderRoute: typeof HospitalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews_/write': {
      id: '/reviews_/write'
      path: '/reviews/write'
      fullPath: '/reviews/write'
      preLoaderRoute: typeof ReviewsWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialities/': {
      id: '/specialities/'
      path: '/specialities'
      fullPath: '/specialities/'
      preLoaderRoute: typeof SpecialitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialities/$slug': {
      id: '/specialities/$slug'
      path: '/specialities/$slug'
      fullPath: '/specialities/$slug'
      preLoaderRoute: typeof SpecialitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialities/$slug_/$city': {
      id: '/specialities/$slug_/$city'
      path: '/specialities/$slug/$city'
      fullPath: '/specialities/$slug/$city'
      preLoaderRoute: typeof SpecialitiesSlugCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AskAQuestionRoute: AskAQuestionRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CostRoute: CostRoute,
  DoctorOnboardingRoute: DoctorOnboardingRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  EmiCalculatorRoute: EmiCalculatorRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsuranceEligibilityRoute: InsuranceEligibilityRoute,
  NoCostEmiRoute: NoCostEmiRoute,
  PatientHelpRoute: PatientHelpRoute,
  PregnancyDueDateCalculatorRoute: PregnancyDueDateCalculatorRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDoctorsDotxmlRoute: SitemapDoctorsDotxmlRoute,
  SitemapHospitalsDotxmlRoute: SitemapHospitalsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurgeryCostCalculatorRoute: SurgeryCostCalculatorRoute,
  TermsRoute: TermsRoute,
  AdminSignupRoute: AdminSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  CostSlugRoute: CostSlugRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  HospitalsSlugRoute: HospitalsSlugRoute,
  LocationsCityRoute: LocationsCityRoute,
  ReviewsWriteRoute: ReviewsWriteRoute,
  SpecialitiesSlugRoute: SpecialitiesSlugRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  SpecialitiesIndexRoute: SpecialitiesIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
  SpecialitiesSlugCityRoute: SpecialitiesSlugCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
